### PR TITLE
Establishes c4model standard

### PR DESCRIPTION
**Pull request by Zk2u**
Co-Authored-By: @cryptopanter

```
Proposed release title: A Young Lady's Illustrated Primer
Proposed release tag: v2
Proposed release name: AYLIP/v2
```

### CODE REVIEW

**Review by cryptopanter — DISMISSED** [review]
That's good

**Comment by 314159265359879** [comment]
Okay I added the Notations chapter, the image is inserted now too, could have been smaller hehe.

**Review by cryptopanter — DISMISSED** [review]
Looks good

**Comment by 314159265359879** [comment]
> Looks good

Have one more look please I added a brief introduction to the top from the daoOS repo.

**Review by 314159265359879 — DISMISSED** [review]
LGTM

**Comment by Zk2u** [comment]
This PR will not be accepting anymore changes. It is now in `beta` and awaiting an L3 project to implement it.

It has been released as a pre-release [here](https://github.com/labs3/standards/releases/tag/v2-beta-1) as `AYLIP/v2-beta-1`.

**Pull request merged**
