### PR TITLE
Change naming scheme

### PR DESCRIPTION
**Pull request by cryptopanter**
Let's change the Standard identifications into Syv-00/V0 naming standard.
Example: Syv-01/V2 (version2)

### CODE REVIEW

**Comment by Zk2u** [comment]
I don't think 'Syv' is the best prefix. We need something else IMO.

**Comment by 314159265359879** [comment]
> 
> 
> I don't think 'Syv' is the best prefix. We need something else IMO.

what about SyvSt for Syvita Standard?

**Comment by Zk2u** [comment]
Standard grouped releases named in format:
Syvita standards Release vX

`SyvR-vX` (sy-ver-vee-X)

where X is a single-digit unique incremental integer (eg `SyvR-v4`)

Then individual standards named as
Syvita Project Standard XX

`Syv-XX` (syv-XX)

where XX is a double-digit unique incremental integer (eg `Syv-01`)

**Comment by asma-rana** [comment]
I have reviewed and acknowledge:
Standard Grouped Releases as SySRvX  (x=number as 1,2... )
Individual Project Standard as SyPS-XX (xx=number as 01,02,03 ...)

**Review by Zk2u — DISMISSED** [review]

**Review by Zk2u — APPROVED** [review]

**Review by 314159265359879 — APPROVED** [review]
LGTM

**Pull request merged**
